ALTER USER SYSTEM IDENTIFIED BY oracle ACCOUNT UNLOCK;
ALTER USER SYS IDENTIFIED BY oracle ACCOUNT UNLOCK;
ALTER USER MOHAMED IDENTIFIED BY chouikh ACCOUNT UNLOCK;
ALTER USER ANONYMOUS ACCOUNT UNLOCK;
EXEC DBMS_XDB.SETHTTPPORT(8080);
COMMIT;
EXIT;
